'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),C=require('../core.js');
const W=require('./writer-harness.js').loadEditorInternals(path.join(root,'index.html'));
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'world-catalog.js'),'utf8'),ctx);
const world=ctx.window.FCWorld;
const sample=JSON.parse(fs.readFileSync(path.join(root,'examples/depot_runs.fcstory'),'utf8'));
let count=0;
function test(name,fn){fn();count++;console.log('PASS:',name);}
function compile(p=sample){return C.compile(p,W,world);}
test('complete quest has four state entries, stable choices, and exact two-ride goal',()=>{const r=compile();assert.deepEqual(r.errors,[]);assert.equal(r.bundle.quests[0].objectives[0].required,2);assert.equal(r.bundle.dialogues[0].entries.length,4);assert.equal(r.bundle.npcs.find(n=>n.id==='froggy').topics[0].dialogue,'fc_depot_runs_dialogue');assert.equal(r.bundle.dialogues[0].nodes[0].choices[0].effects[0].kind,'start_quest');});
test('saved source roundtrip reproduces identical export',()=>assert.deepEqual(compile(C.clone(sample)).bundle,compile().bundle));
test('ordinary text edits preserve quest and once-choice identity',()=>{const p=C.clone(sample);p.documents[0].text=p.documents[0].text.replace('Zajmę się tym.','Jasne.');assert.equal(compile(p).bundle.dialogues[0].nodes[0].choices[0].id,'accept');});
test('stamping assigns new IDs once and preserves all existing IDs',()=>{const text=sample.documents[0].text.replace('Do zobaczenia.{-1}','Do zobaczenia.{-1}\nDruga odpowiedź.{-1}');const once=C.stabilize(text,W);assert.equal(C.stabilize(once,W),once);assert.ok(once.includes('@fc:choice accept'));const p=C.indexed(once,W);assert.ok(p.stages[1].nodes[1].options.every(o=>C.validId(o.stableId)));});
test('copy-pasted persistent markers are rejected instead of renumbering saved choices',()=>{const p=C.clone(sample);p.documents[0].text=p.documents[0].text.replace('@fc:choice decline','@fc:choice accept');assert.ok(compile(p).errors.some(e=>e.message.includes('powtórzone')));});
test('freeform conditions cannot silently become gameplay',()=>{const p=C.clone(sample);p.documents[0].text=p.documents[0].text.replace('##END','//warunek: zapłać 20 CR -> {ETAP_3}\n##END');assert.ok(compile(p).errors.some(e=>e.message.includes('//warunek')));});
test('fractional ride counts fail at authoring boundary',()=>{const p=C.clone(sample);p.documents[0].objectives[0].required=2.001;assert.ok(compile(p).errors.some(e=>e.message.includes('całkowita')));});
test('missing start and turn-in actions are explained',()=>{const p=C.clone(sample);p.documents[0].choices={};assert.equal(compile(p).errors.filter(e=>/żadna odpowiedź/.test(e.message)).length,2);});
test('dangling text anchors fail export',()=>{const p=C.clone(sample);p.documents[0].text=p.documents[0].text.replace('Zajmę się tym.{ETAP_2}','Zajmę się tym.{missing}');assert.ok(compile(p).errors.some(e=>e.message.includes('missing')));});
test('deleting an entry stage cannot silently discard its configuration',()=>{const p=C.clone(sample);p.documents[0].stages.ETAP_99={status:'active',conditions:[]};assert.ok(compile(p).errors.some(e=>e.message.includes('ETAP_99')));});
test('known world names map to stable platform IDs',()=>{assert.equal(world.stops.length,25);assert.ok(world.stops.some(s=>s.id==='depot'));const p=C.clone(sample);p.documents[0].objectives[0].destination_id='Pad0';assert.ok(compile(p).errors.some(e=>e.message.includes('nieznana platforma')));});
test('two independent documents may reuse local anchors and marker labels',()=>{const p=C.clone(sample),d=C.wireTemplate(C.newDocument('maya','MAYA','maya_work'));p.documents.push(d);assert.deepEqual(compile(p).errors,[]);assert.equal(compile(p).bundle.dialogues.length,2);});
test('dialogue condition/effect values survive compilation',()=>{const p=C.clone(sample);p.fact_ids.push('promised');p.documents[0].choices.accept.conditions=[C.condition('credits','',20)];p.documents[0].choices.accept.effects.push(C.effect('spend','',20),C.effect('set_fact','promised',1));const c=compile(p).bundle.dialogues[0].nodes[0].choices[0];assert.equal(c.conditions[0].amount,20);assert.deepEqual(c.effects.map(x=>x.kind),['start_quest','spend','set_fact']);});
function branching(){const p=C.clone(sample),d=p.documents[0],a=d.objectives[0],b=C.objective(),c=C.objective();p.fact_ids.push('route');b.id='north';c.id='south';a.transitions=[{target:'north',conditions:[C.condition('fact','route')]},{target:'south',conditions:[]}];b.transitions=[{target:'',conditions:[]}];c.transitions=[{target:'',conditions:[]}];d.objectives.push(b,c);return p;}
test('conditional objective graph compiles with explicit fallback',()=>assert.deepEqual(compile(branching()).errors,[]));
test('objective cycles and missing fallback are rejected',()=>{const p=branching();p.documents[0].objectives[1].transitions[0].target=p.documents[0].objectives[0].id;assert.ok(compile(p).errors.some(e=>e.message.includes('pętlę')));p.documents[0].objectives[0].transitions.pop();assert.ok(compile(p).errors.some(e=>e.message.includes('ostatnie przejście')));});
test('unreachable gameplay objectives are rejected',()=>{const p=branching();p.documents[0].objectives[0].transitions[0].target='south';assert.ok(compile(p).errors.some(e=>e.message.includes('nieosiągalny')));});
test('unsupported commands and unknown facts fail validation',()=>{const p=C.clone(sample);p.documents[0].choices.accept.effects.push(C.effect('call_method','anything'));assert.ok(compile(p).errors.some(e=>e.message.includes('nieprawidłowy skutek')));p.documents[0].choices.accept.effects=[C.effect('set_fact','unknown')];assert.ok(compile(p).errors.some(e=>e.message.includes('nieznany fact')));});
test('standalone conversation exports without imaginary quest state',()=>{const p=C.clone(sample);p.documents=[C.newConversation('maya','MAYA')];const r=compile(p);assert.deepEqual(r.errors,[]);assert.equal(r.bundle.quests.length,0);assert.equal(r.bundle.dialogues[0].entries.length,1);});
test('changing interlocutor updates speaker text and the reward recipient',()=>{const p=C.clone(sample);C.updateField(p,'documents.0.npc','maya');assert.equal(p.documents[0].turn_in_npc,'maya');assert.ok(!p.documents[0].text.includes('FROGGY'));assert.deepEqual(compile(p).errors,[]);});
test('renaming NPC and quest preserves attached mechanics',()=>{const p=C.clone(sample),i=p.npcs.findIndex(n=>n.id==='froggy');C.updateField(p,'npcs.'+i+'.display_name','FROG');C.updateField(p,'documents.0.id','new_job');assert.equal(p.documents[0].choices.accept.effects[0].key,'new_job');assert.deepEqual(compile(p).errors,[]);});
test('renaming branch targets and facts preserves both routes',()=>{const p=branching();C.updateField(p,'documents.0.objectives.1.id','other_north');C.updateField(p,'fact_ids.0','new_route');assert.equal(p.documents[0].objectives[0].transitions[0].target,'other_north');assert.equal(p.documents[0].objectives[0].transitions[0].conditions[0].key,'new_route');assert.deepEqual(compile(p).errors,[]);});
test('claim conversation must belong to designated recipient',()=>{const p=C.clone(sample);p.documents[0].turn_in_npc='maya';assert.ok(compile(p).errors.some(e=>e.message.includes('wyznaczonym odbiorcą')));});
test('world pickers expose all 63 stable vehicle IDs and 12 models',()=>{assert.equal(world.vehicles.length,63);assert.equal(world.models.length,12);assert.ok(world.vehicles.some(v=>v.id==='resident/mechanic'));});
test('changing event type clears incompatible hidden filters',()=>{const p=C.clone(sample),o=p.documents[0].objectives[0];o.vehicle_id='ari_cab';C.updateField(p,'documents.0.objectives.0.event','medicine_delivered');assert.equal(o.destination_id,'');assert.equal(o.vehicle_id,'');assert.deepEqual(compile(p).errors,[]);});
test('stale filters that a built-in event never emits block export',()=>{const p=C.clone(sample);p.documents[0].objectives[0].event='credits_earned';assert.ok(compile(p).errors.some(e=>e.message.includes('nie wysyła platformy')));});
function authoredBlank(mode='event'){
  const p=C.createQuest(sample,{scope:'new',title:'Sprawdź auto',npc_id:'froggy'},world),d=p.documents[0];
  d.text=d.text.replace(/⟪Uzupełnij: [^⟫]+⟫/g,'Sprawdź auto i wróć do mnie.');
  const o=C.emptyObjective();o.description='Wsiądź do auta.';o.mode=mode;
  if(mode==='event'){o.event='vehicle_entered';o.vehicle_id='ari_cab';}else{o.conditions=[C.condition('credits','',100)];}
  d.objectives.push(o);return p;
}
test('new quest adds a blank draft while preserving the existing project',()=>{const before=JSON.stringify(sample),p=C.createQuest(sample,{scope:'current',title:'Moje zadanie',npc_id:'maya'},world),d=p.documents.at(-1);assert.equal(p.id,sample.id);assert.deepEqual(p.documents[0],sample.documents[0]);assert.equal(JSON.stringify(sample),before);assert.equal(d.title,'Moje zadanie');assert.equal(d.npc,'maya');assert.equal(d.turn_in_npc,'maya');assert.equal(d.objectives.length,0);assert.equal(d.reward_credits,0);assert.ok(!d.text.includes('Depot'));assert.notEqual(d.id,sample.documents[0].id);});
test('separate project contains only the new quest and a distinct import identity',()=>{const p=C.createQuest(sample,{scope:'new',title:'Od zera',npc_id:'froggy'},world);assert.notEqual(p.id,sample.id);assert.equal(p.documents.length,1);assert.equal(p.documents[0].title,'Od zera');assert.deepEqual(p.items,[]);assert.deepEqual(p.fact_ids,[]);});
test('blank draft cannot export prompts or an absent goal as playable content',()=>{const p=C.createQuest(sample,{scope:'new',title:'Szkic',npc_id:'froggy'},world),errors=compile(p).errors;assert.equal(errors.filter(e=>e.message.includes('zastąp wskazówkę')).length,4);assert.ok(errors.some(e=>e.message.includes('przynajmniej jeden cel')));assert.ok(!errors.some(e=>e.message.includes('żadna odpowiedź')));});
test('completed blank quest exports all state entries and correctly connected actions',()=>{const p=authoredBlank(),r=compile(p),id=p.documents[0].id;assert.deepEqual(r.errors,[]);assert.equal(r.bundle.quests[0].objectives[0].vehicle_id,'ari_cab');assert.equal(r.bundle.quests[0].objectives[0].required,1);assert.equal(r.bundle.dialogues[0].entries.length,4);const actions=r.bundle.dialogues[0].nodes.flatMap(n=>n.choices.flatMap(c=>c.effects));assert.deepEqual(actions.map(e=>[e.kind,e.key]),[['start_quest',id],['turn_in',id]]);assert.equal(r.bundle.quests[0].authoring,undefined);});
test('state goal created from scratch needs no hidden event setup',()=>{const r=compile(authoredBlank('state'));assert.deepEqual(r.errors,[]);assert.equal(r.bundle.quests[0].objectives[0].event,'ride_completed');assert.equal(r.bundle.quests[0].objectives[0].conditions[0].amount,100);});
test('creator wires a newly named NPC to the quest without replacing existing profiles',()=>{const p=C.createQuest(sample,{scope:'current',title:'Kontakt',npc_id:'__new__',new_npc_name:'Ivo'},world),d=p.documents.at(-1),n=p.npcs.find(n=>n.id===d.npc);assert.equal(n.display_name,'IVO');assert.equal(n.existing,false);assert.equal(d.turn_in_npc,n.id);assert.ok(d.text.includes('*IVO*'));assert.deepEqual(p.npcs.slice(0,-1),sample.npcs);});
test('invalid creator input leaves the source project intact',()=>{const before=JSON.stringify(sample);assert.throws(()=>C.createQuest(sample,{scope:'current',title:'',npc_id:'maya'},world));assert.throws(()=>C.createQuest(sample,{scope:'current',title:'Quest',npc_id:'missing'},world));assert.throws(()=>C.createQuest(sample,{scope:'new',title:'Quest',npc_id:'__new__',new_npc_name:'*GRACZ*'},world));assert.equal(JSON.stringify(sample),before);});
test('blank-project save roundtrip retains guides and stable actions',()=>{const p=authoredBlank();assert.deepEqual(compile(JSON.parse(JSON.stringify(p))).bundle,compile(p).bundle);assert.equal(p.documents[0].authoring.from_scratch,true);});
test('empty added objective has no inherited destination or assumed event',()=>{const o=C.emptyObjective();assert.equal(o.description,'');assert.equal(o.destination_id,'');assert.equal(o.event,'');assert.equal(o.required,1);});
test('upstream original SHA remains unchanged when available',()=>{const provenance=JSON.parse(fs.readFileSync(path.join(root,'UPSTREAM.json'),'utf8')),upstream=path.resolve(root,'../../../quest_editor/index.html');if(fs.existsSync(upstream))assert.equal(require('node:crypto').createHash('sha256').update(fs.readFileSync(upstream)).digest('hex'),provenance.source_sha256);});
fs.writeFileSync(path.join(root,'examples/depot_runs.narrative.json'),JSON.stringify(compile().bundle,null,2)+'\n');
console.log('Story compiler:',count,'checks passed.');
