/* Flying Cab Story Editor 1.1. The upstream writer is an independent copy. */
(function(){
  'use strict';
  const C=window.FCStory,W=window.FlyingCabWriter,world=window.FCWorld||{};
  if(!C||!W)throw new Error('Nie udało się uruchomić edytora Flying Cab.');
  const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const STORAGE='flying-cab-story-project-v1';
  let cacheAllowed=true;
  let project=C.example(world),docIndex=0,tab='quest',goalIndex=0,stageId='',choiceId='',npcId='froggy',dirty=false,loading=false,timer=null;
  let undo=[],redo=[];
  window.FlyingCabEditor={getProject:()=>C.clone(project),compile:()=>compile(),loadProject:p=>loadProject(p),version:'1.1'};
  const main=$('.app-main'), workspace=document.createElement('div');workspace.id='fc-workspace';main.before(workspace);workspace.append(main);
  const inspector=document.createElement('aside');inspector.id='fc-inspector';workspace.append(inspector);
  inspector.innerHTML='<nav class="fc-tabs" aria-label="Ustawienia fabuły"></nav><div id="fc-properties"></div>';
  $('.app-header h1').textContent='FLYING CAB / FABUŁA';
  const actions=document.createElement('div');actions.className='fc-actions';
  actions.innerHTML='<select class="fc-project-select" id="fc-document" aria-label="Quest lub rozmowa"></select><button class="btn" id="fc-new" title="Utwórz własny quest od zera">+ Nowy quest</button><button class="btn" id="fc-new-talk">+ Rozmowa</button><button class="btn" id="fc-open">Otwórz projekt</button><button class="btn" id="fc-save">Zapisz projekt</button><button class="btn primary" id="fc-export">Eksport do Godota</button><button class="btn" id="fc-toggle">Ustawienia</button><span id="fc-dirty">Przykład</span><input id="fc-file" type="file" accept=".fcstory,.json" hidden><input id="fc-text-file" type="file" accept=".txt,.md" hidden>';
  $('.app-header h1').after(actions);
  const results=document.createElement('section');results.id='fc-results';results.hidden=true;results.setAttribute('role','dialog');results.setAttribute('aria-modal','true');results.setAttribute('aria-labelledby','fc-result-title');results.innerHTML='<div class="fc-result-head"><h2 id="fc-result-title"></h2><button class="fc-mini" id="fc-result-close">Zamknij</button></div><div id="fc-result-body"></div>';document.body.append(results);
  for(const select of document.querySelectorAll('select'))for(const option of select.options){if(option.value==='play')option.textContent='Czytanie';if(option.value==='flow')option.textContent='Flow rozmów';}
  $('#tab-flow').textContent='Flow rozmów';
  const playNote=document.createElement('div');playNote.className='fc-playing-note';playNote.textContent='Przejście przez tekst. Skutki wyborów i zdarzenia świata sprawdzaj w podglądzie Godota.';$('#play-view').prepend(playNote);
  const props=$('#fc-properties');
  function doc(){return project.documents[docIndex];}
  function get(path){return path.split('.').reduce((v,k)=>v?.[k],project);}
  function set(path,value){const keys=path.split('.'),last=keys.pop();keys.reduce((v,k)=>v[k],project)[last]=value;}
  function remember(){undo.push(JSON.stringify(project));if(undo.length>60)undo.shift();redo=[];}
  function cache(){if(!cacheAllowed)return;try{localStorage.setItem(STORAGE,JSON.stringify({project,docIndex}));}catch(e){$('#fc-dirty').textContent='Zapisz plik — szkic niedostępny';}}
  function changed(){dirty=true;$('#fc-dirty').textContent='Niezapisane zmiany';cache();W.clean();}
  function syncText(){if(loading||!doc())return;if(doc().text!==W.getText()){doc().text=W.getText();changed();const guide=props.querySelector('.fc-start-guide');if(guide)guide.outerHTML=starterGuide(doc());}}
  function stabilize(){syncText();if(!doc())return;const old=W.getText(),text=C.stabilize(old,W);if(old!==text){doc().text=text;loading=true;W.setText(text);loading=false;changed();}}
  function selectDoc(index,syncExisting=true){if(syncExisting)syncText();docIndex=Math.max(0,Math.min(index,project.documents.length-1));goalIndex=0;stageId='';choiceId='';loading=true;W.load(doc()?.text||'');loading=false;W.clean();renderDocumentPicker();render();cache();}
  function loadProject(p){C.checkProject(p);project=C.clone(p);undo=[];redo=[];docIndex=0;selectDoc(0,false);dirty=false;cacheAllowed=true;$('#fc-dirty').textContent='Projekt wczytany';cache();}
  function renderDocumentPicker(){const select=$('#fc-document');select.innerHTML=project.documents.map((d,i)=>'<option value="'+i+'">'+esc((d.kind==='quest'?'◆ ':'◇ ')+d.title)+'</option>').join('');select.value=String(docIndex);}
  function options(values,value){return values.map(v=>{const pair=Array.isArray(v)?v:[v,v];return '<option value="'+esc(pair[0])+'"'+(String(pair[0])===String(value)?' selected':'')+'>'+esc(pair[1])+'</option>';}).join('');}
  function field(label,path,type='text',values=null){const value=get(path);let input;if(type==='select')input='<select class="fc-field" data-path="'+path+'">'+options(values||[],value)+'</select>';else if(type==='textarea')input='<textarea class="fc-field" data-path="'+path+'">'+esc(value)+'</textarea>';else if(type==='check')return '<label class="fc-check"><input type="checkbox" data-path="'+path+'"'+(value?' checked':'')+'>'+esc(label)+'</label>';else if(type==='multi')input='<select class="fc-field" multiple data-path="'+path+'" data-type="multi">'+(values||[]).map(v=>'<option value="'+esc(v[0])+'"'+(value?.includes(v[0])?' selected':'')+'>'+esc(v[1])+'</option>').join('')+'</select>';else input='<input class="fc-field" type="'+type+'" '+(type==='number'?'min="0" step="any" ':'')+'data-path="'+path+'" value="'+esc(value)+'">';return '<label class="fc-label">'+esc(label)+input+'</label>';}
  function btn(label,action,path='',cls='fc-add'){return '<button class="'+cls+'" data-action="'+action+'" data-path="'+path+'">'+esc(label)+'</button>';}
  function records(kind){const byId=new Map();const values=kind==='quest'?[...(world.quests||[]),...project.documents.filter(d=>d.kind==='quest')]:kind==='item'?[...(world.items||[]),...project.items]:kind==='npc'?project.npcs:kind==='fact'?[...(world.fact_ids||[]),...project.fact_ids].map(id=>({id})):kind==='access'?[...(world.access_ids||[]),...project.access_ids].map(id=>({id})):kind==='custom'?[...(world.custom_events||[]),...project.custom_events].map(id=>({id})):kind==='vehicle'?(world.vehicles||[]):kind==='model'?(world.models||[]):(world.stops||[]);for(const x of values)byId.set(x.id,[x.id,x.title||x.display_name||x.name||x.id]);return [...byId.values()];}
  function keyField(label,path,kind,empty='— wybierz —'){const values=[['',empty],...records(kind)];if(get(path)&&!values.some(x=>x[0]===get(path)))values.push([get(path),get(path)+' (brak w katalogu)']);return field(label,path,'select',values);}
  function conditionList(path){const list=get(path)||[];return list.map((c,i)=>{const p=path+'.'+i;let body=field('Warunek',p+'.kind','select',Object.entries(C.CONDITIONS));const keyKinds={quest_status:'quest',fact:'fact',item:'item',access:'access',vehicle_id:'vehicle',vehicle_model:'model'};if(keyKinds[c.kind])body+=keyField('Dotyczy',p+'.key',keyKinds[c.kind]);if(c.kind==='quest_status')body+=field('Stan',p+'.status','select',Object.entries(C.STATUSES));else if(!['campaign_active','access','vehicle_id','vehicle_model'].includes(c.kind))body+='<div class="fc-row">'+field('Porównanie',p+'.comparison','select',['>=','<=','==','!=','>','<'])+field('Wartość',p+'.amount','number')+'</div>';body+=field('Odwróć warunek (NIE)',p+'.invert','check')+field('Powód blokady dla gracza',p+'.reason');return '<div class="fc-card"><div class="fc-card-head">Wszystkie warunki muszą pasować'+btn('Usuń','remove',p,'fc-mini danger')+'</div>'+body+'</div>';}).join('')+btn('+ Warunek','add-condition',path);}
  function effectList(path,reward=false){const list=get(path)||[];return list.map((e,i)=>{const p=path+'.'+i,allowed=Object.entries(C.EFFECTS).filter(([k])=>!reward||['set_fact','grant_item','grant_access','revoke_access'].includes(k));let body=field('Skutek wyboru',p+'.kind','select',allowed);const kinds={start_quest:'quest',turn_in:'quest',set_fact:'fact',grant_item:'item',remove_item:'item',grant_access:'access',revoke_access:'access'};if(kinds[e.kind])body+=keyField('Dotyczy',p+'.key',kinds[e.kind]);if(!['start_quest','turn_in','grant_access','revoke_access'].includes(e.kind))body+=field(e.kind==='start_campaign'?'Czas początkowy (sekundy)':e.kind==='set_fact'?'Wartość faktu':'Ilość / kwota',p+'.amount','number');if(['buy_medicine','deliver_medicine'].includes(e.kind))body+=field(e.kind==='buy_medicine'?'Cena za dawkę (CR)':'Czas dodawany za dawkę (sekundy)',p+'.value','number');return '<div class="fc-card"><div class="fc-card-head">'+(i+1)+'. skutek'+btn('Usuń','remove',p,'fc-mini danger')+'</div>'+body+'</div>';}).join('')+btn('+ Skutek','add-effect',path);}
  function detail(title,body,open=false){return '<details class="fc-section"'+(open?' open':'')+'><summary>'+title+'</summary>'+body+'</details>';}
  function title(text,note){return '<h2 class="fc-title">'+esc(text)+'</h2><p class="fc-note">'+esc(note)+'</p>';}
  function parsed(){return C.indexed(doc()?.text||'',W);}
  function starterGuide(d){
    if(d.kind!=='quest')return '';
    if(!d.authoring?.from_scratch)return '<div class="fc-start-prompt"><strong>Chcesz zacząć własny quest?</strong>'+btn('Nowy quest od zera','new-quest')+'</div>';
    if(d.authoring.guide_dismissed)return '';
    const missing=(d.text.match(/⟪Uzupełnij:/g)||[]).length;
    const goals=d.objectives.length&&d.objectives.every(o=>o.description.trim()&&(o.mode==='state'?o.conditions.length:Object.hasOwn(C.EVENTS,o.event)));
    return '<section class="fc-start-guide"><h2>Zacznij tutaj</h2><p>Przyjęcie zadania i oddanie u zleceniodawcy są już połączone.</p>'+btn((goals?'✓ ':'1. ')+'Określ cel zadania','guide-goals')+'<p>Co ma zrobić gracz? Wybierz zdarzenie albo sprawdzany stan.</p>'+btn((missing?'2. ':'✓ ')+'Napisz rozmowę','guide-text')+'<p>'+(missing?'Do zastąpienia: '+missing+' żółte wskazówki. Kliknięcie przeniesie Cię do pierwszej.':'Wskazówki zastąpione. Możesz dalej rozbudować rozmowę.')+'</p>'+btn('3. Uzupełnij opis i nagrodę','guide-details')+'<p>Opis trafi do dziennika. Nagroda domyślnie wynosi 0 CR.</p>'+btn('Sprawdź gotowość do eksportu','validate')+btn('Ukryj wskazówki','hide-guide','','fc-mini')+'</section>';
  }
  function openCreator(){
    syncText();
    showResult('Nowy quest od zera','<form id="fc-create-form"><p class="fc-note">Nadaj nazwę i wybierz, kto zleca zadanie. Powstanie pusty quest z połączonym przyjęciem i oddaniem.</p><label class="fc-label">Gdzie utworzyć quest?<select class="fc-field" id="fc-create-scope"><option value="current">W bieżącym projekcie: '+esc(project.title)+'</option><option value="new">W nowym, osobnym projekcie</option></select></label><p class="fc-note" id="fc-create-scope-note"></p><button type="button" class="fc-mini" id="fc-create-save" hidden>Pobierz bieżący projekt przed zmianą</button><label class="fc-label">Nazwa questa<input class="fc-field" id="fc-create-title" required maxlength="100" placeholder="np. Zaginiona przesyłka" autocomplete="off"></label><label class="fc-label">Zleceniodawca<select class="fc-field" id="fc-create-npc" required></select></label><label class="fc-label" id="fc-create-name-label" hidden>Imię nowej postaci<input class="fc-field" id="fc-create-name" maxlength="60" autocomplete="off"></label><p class="fc-note" id="fc-create-npc-note"></p><div id="fc-create-error" class="fc-error" role="alert" hidden></div><div class="fc-create-footer"><button type="button" class="fc-mini" id="fc-create-cancel">Anuluj</button><button type="submit" class="btn fc-create-primary" id="fc-create-submit">Utwórz quest</button></div><p class="fc-note">Projekt to zestaw questów i rozmów zapisywany w jednym pliku. Nowy quest w bieżącym projekcie zachowuje dotychczasowe dokumenty.</p></form>');
    const scope=$('#fc-create-scope'),npc=$('#fc-create-npc'),name=$('#fc-create-name');
    const npcNote=()=>{const isNew=npc.value==='__new__';$('#fc-create-name-label').hidden=!isNew;name.required=isNew;$('#fc-create-npc-note').textContent=isNew?'Profil i rozmowy przygotuje edytor. Po imporcie umieścisz postać na mapie w Godocie.':'Przyjęcie i oddanie zadania będą dostępne u tej postaci.';};
    const scopeNote=()=>{
      const old=npc.value,list=scope.value==='new'?(world.npcs||project.npcs.filter(n=>n.existing)):project.npcs;
      npc.innerHTML=options([['','— Wybierz postać —'],...list.map(n=>[n.id,n.display_name]),['__new__','+ Utwórz nową postać']],old);
      if(![...npc.options].some(o=>o.value===old))npc.value='';
      const separate=scope.value==='new';
      $('#fc-create-scope-note').textContent=separate?'Powstanie osobny projekt zawierający tylko nowy quest, bez przykładu i poprzednich zadań. Zapisz bieżący projekt przed przełączeniem.':'Obecne dokumenty zostają zachowane. To właściwy wybór przy rozbudowie tej samej opowieści.';
      $('#fc-create-save').hidden=!separate;
      $('#fc-create-submit').textContent=separate?'Utwórz projekt i quest':'Utwórz quest';npcNote();
    };
    scope.addEventListener('change',scopeNote);npc.addEventListener('change',npcNote);
    $('#fc-create-save').addEventListener('click',saveProject);$('#fc-create-cancel').addEventListener('click',closeResult);
    $('#fc-create-form').addEventListener('submit',e=>{
      e.preventDefault();syncText();
      try{
        const next=C.createQuest(project,{scope:scope.value,title:$('#fc-create-title').value,npc_id:npc.value,new_npc_name:name.value},world);
        remember();project=next;tab='quest';props.innerHTML='';inspector.hidden=false;cacheAllowed=true;closeResult();selectDoc(project.documents.length-1,false);changed();props.scrollTop=0;
      }catch(error){$('#fc-create-error').textContent=error.message;$('#fc-create-error').hidden=false;}
    });
    scopeNote();$('#fc-create-title').focus();
  }
  function render(){
    const scroll=props.scrollTop, opened=new Map([...props.querySelectorAll('details')].map(e=>[e.querySelector('summary')?.textContent,e.open]));
    $('.fc-tabs').innerHTML=Object.entries({quest:'Zadanie',dialogue:'Rozmowa',choice:'Odpowiedź',npc:'Postacie',catalog:'Katalog',preview:'Podgląd',help:'Pomoc'}).map(([k,v])=>'<button data-tab="'+k+'" class="'+(tab===k?'active':'')+'">'+v+'</button>').join('');
    if(!doc()){props.innerHTML=title('Dodaj zadanie','Kliknij + Nowy quest, aby rozpocząć.');return;}
    const d=doc(),p='documents.'+docIndex;let html='';
    if(tab==='quest'){
      html=starterGuide(d)+title('Ustawienia zadania','Teksty piszesz obok. Tutaj określasz, co ma wydarzyć się w grze.')+field('Tytuł',p+'.title')+'<span class="fc-pill">'+(d.kind==='quest'?'Zadanie z celami':'Samodzielna rozmowa / sklep')+'</span>'+keyField('Rozmówca',p+'.npc','npc')+field('Temat rozmowy',p+'.topic_title');
      if(d.kind==='quest'){
        html+=field('Opis w dzienniku',p+'.description','textarea')+field('Zadanie główne / poboczne',p+'.category','select',[['side','Poboczne'],['main','Główne']]);
        html+='<div class="fc-section" id="fc-goals-section"><strong>Cele zadania</strong><p class="fc-note">Domyślnie po kolei. Przy celu możesz ustawić alternatywne przejścia.</p>'+d.objectives.map((o,i)=>'<button class="fc-goal '+(i===goalIndex?'active':'')+'" data-goal="'+i+'"><span>'+(i+1)+'</span>'+esc(o.description||'Nowy cel — uzupełnij opis')+'</button>').join('')+btn('+ Dodaj cel','add-objective',p+'.objectives')+btn('Pokaż przebieg celów','goal-flow')+'</div>';
        goalIndex=Math.min(goalIndex,d.objectives.length-1);const o=d.objectives[goalIndex],op=p+'.objectives.'+goalIndex;
        if(o){html+='<div class="fc-card"><div class="fc-card-head">Cel '+(goalIndex+1)+'<span>'+btn('↑','up',op,'fc-mini')+' '+btn('Usuń','remove',op,'fc-mini danger')+'</span></div>'+field('Opis celu',op+'.description','textarea')+field('Sposób zaliczenia',op+'.mode','select',[['event','Zliczaj nowe zdarzenia'],['state','Sprawdź posiadany stan']]);
          if(o.mode==='event'){html+=field('Zdarzenie',op+'.event','select',[['','— Wybierz zdarzenie —'],...Object.entries(C.EVENTS)]);if(o.event){html+=field('Wymagana ilość',op+'.required','number');if(o.event==='custom')html+=keyField('Zdarzenie zarejestrowane w grze',op+'.custom_event','custom');if(['ride_completed','passenger_boarded'].includes(o.event))html+=keyField('Platforma początkowa',op+'.origin_id','stop','Dowolna')+keyField('Platforma docelowa',op+'.destination_id','stop','Dowolna');if(['medicine_delivered'].includes(o.event))html+=keyField('Odbiorca',op+'.target_id','npc','Dowolny');else if(o.event==='fuel_purchased')html+=keyField('Miejsce tankowania',op+'.target_id','stop','Dowolne');else if(!['ride_completed','passenger_boarded','vehicle_repaired'].includes(o.event))html+=field('Obiekt / obszar (ID)',op+'.target_id');if(!['credits_earned','medicine_delivered'].includes(o.event))html+=keyField('Pojazd',op+'.vehicle_id','vehicle','Dowolny');}}
          html+=detail('Warunki celu',conditionList(op+'.conditions'),o.mode==='state');
          html+=detail('Rozwidlenia po wykonaniu celu',(o.transitions||[]).map((t,i)=>{const tp=op+'.transitions.'+i;return '<div class="fc-card fc-route"><div class="fc-card-head">'+(i+1)+'. '+(t.conditions.length?'Jeśli warunki pasują':'W pozostałych przypadkach')+btn('Usuń','remove',tp,'fc-mini danger')+'</div>'+field('Przejdź do',tp+'.target','select',[['','Zakończ cele / odbiór nagrody'],...d.objectives.filter(x=>x.id!==o.id).map(x=>[x.id,x.description])])+conditionList(tp+'.conditions')+'</div>';}).join('')+btn('+ Rozwidlenie','add-route',op+'.transitions')+'<p class="fc-note">Pierwsza pasująca reguła wygrywa. Ostatnia musi być bez warunków. Pętle celów są blokowane.</p>');html+='<details class="fc-meta"><summary>Identyfikator celu</summary>'+field('Trwałe ID',op+'.id')+'</details></div>';}
        html+=detail('Rozpoczęcie',field('Wymagane wcześniejsze zadania',p+'.prerequisites','multi',records('quest').filter(x=>x[0]!==d.id))+field('Rozpocznij automatycznie po spełnieniu wymagań',p+'.auto_start','check')+conditionList(p+'.conditions'));
        html+=detail('Oddanie i nagrody',field('Wymagaj osobistego odbioru nagrody',p+'.requires_turn_in','check')+(d.requires_turn_in?keyField('Oddaj zadanie u',p+'.turn_in_npc','npc'):'')+field('Nagroda (CR)',p+'.reward_credits','number')+effectList(p+'.rewards',true),true);
      }
      html+=detail('Dostępność całego tematu',conditionList(p+'.topic_conditions'));
      html+='<details class="fc-meta"><summary>Wersja i identyfikator</summary>'+field('Trwałe ID dokumentu',p+'.id')+field('Wersja celów',p+'.version','number')+'<p class="fc-note">Zmiana celów już zaimportowanego questa wymaga wyższej wersji i nowej gry lub migracji zapisu. Poprawianie tekstu nie wymaga zwiększania wersji.</p></details>'+btn('Powiel dokument','duplicate-doc')+btn('Wczytaj tekst .txt do tego dokumentu','import-text');
    }else if(tab==='dialogue'){
      const stages=parsed().stages;if(!stages.some(s=>s.id===stageId))stageId=stages[0]?.id||'';
      html=title('Początki rozmowy','Wybierz, który etap ma powitać gracza przy ponownej rozmowie. Reguły są sprawdzane w kolejności etapów.');
      html+='<label class="fc-label">Etap<select class="fc-field" id="fc-stage">'+options(stages.map(s=>[s.id,s.id+' · '+s.title]),stageId)+'</select></label>';
      if(stageId){if(!d.stages[stageId])d.stages[stageId]={status:'none',conditions:[]};const sp=p+'.stages.'+stageId;html+=field('Kiedy zaczynać od tego etapu',sp+'.status','select',[['none','Tylko przez skok z odpowiedzi'],['always','Zawsze / gdy warunki pasują'],...(d.kind==='quest'?Object.entries(C.STATUSES):[])])+conditionList(sp+'.conditions')+btn('Przejdź do tekstu etapu','goto-stage');}
      html+=btn('+ Dodaj etap rozmowy','add-stage')+btn('Uzupełnij ID nowych wypowiedzi','stabilize')+'<p class="fc-note">// @fc: to automatyczne identyfikatory zapisu gry. Zachowuj je przy poprawianiu tekstu. Kotwice {1.1} oraz skoki {ETAP_2} działają jak w dotychczasowym edytorze.</p>';
      for(const id of Object.keys(d.stages))if(!stages.some(s=>s.id===id))html+='<div class="fc-warning">Brak etapu '+esc(id)+btn('Usuń stare ustawienia','delete-key',p+'.stages.'+id,'fc-mini')+'</div>';
    }else if(tab==='choice'){
      const choices=parsed().stages.flatMap(s=>s.nodes.flatMap(n=>n.options.map(o=>({...o,stage:s.id}))));if(!choices.some(c=>c.stableId===choiceId))choiceId=choices[0]?.stableId||'';
      html=title('Warunki i skutki odpowiedzi','Wybierz odpowiedź z listy albo ustaw kursor na jej tekście i kliknij „Z kursora”.')+btn('Wybierz odpowiedź z kursora','choice-cursor');
      html+='<label class="fc-label">Odpowiedź<select class="fc-field" id="fc-choice">'+options(choices.map(c=>[c.stableId,c.stage+' · '+c.text]),choiceId)+'</select></label>';
      if(choiceId){if(!d.choices[choiceId])d.choices[choiceId]={conditions:[],effects:[],once:false,hide_unavailable:false};const cp=p+'.choices.'+choiceId;html+=field('Działanie tylko raz w całej grze',cp+'.once','check')+field('Ukryj odpowiedź, gdy niedostępna',cp+'.hide_unavailable','check')+detail('Warunki dostępności',conditionList(cp+'.conditions'),true)+detail('Skutki w podanej kolejności',effectList(cp+'.effects'),true)+'<p class="fc-note">Cała lista skutków jest zatwierdzana razem. Nieudana płatność nie przyzna przedmiotu.</p>';}
    }else if(tab==='npc'){
      if(!project.npcs.some(n=>n.id===npcId))npcId=project.npcs[0]?.id||'';const i=project.npcs.findIndex(n=>n.id===npcId),np='npcs.'+i;
      html=title('Postacie','Wspólne profile dla wszystkich rozmów i questów.')+'<label class="fc-label">Postać<select class="fc-field" id="fc-npc">'+options(project.npcs.map(n=>[n.id,n.display_name]),npcId)+'</select></label>'+btn('+ Nowa postać','add-npc');
      if(i>=0){const n=project.npcs[i];html+=field('Imię w grze i nagłówkach dialogów',np+'.display_name')+field('Powitanie / wybór tematu',np+'.greeting','textarea')+field('Portret (res://…; opcjonalny)',np+'.portrait');html+='<p class="fc-note">'+(n.existing?'Profil istnieje w grze. Import dopisze tematy i zachowa dotychczasowe rozmowy.':'Po imporcie przeciągnij scenes/narrative/npc.tscn na mapę i przypisz wygenerowany profil. Model ustawiasz na dziecku Visual. Stopy na platformie, Z = 1,2.')+'</p>'+detail('Powiązane dokumenty',project.documents.filter(x=>x.npc===n.id||x.turn_in_npc===n.id).map(x=>'<span class="fc-pill">'+esc(x.title)+'</span>').join(''),true)+'<details class="fc-meta"><summary>Powiązanie z grą</summary>'+field('Trwałe ID',np+'.id')+field('Użyj istniejącego profilu',np+'.existing','check')+'</details>';}
    }else if(tab==='catalog'){
      html=title('Projekt i słowniki','Nazwy są wspólne dla wszystkich dokumentów.')+field('Nazwa projektu', 'title')+field('Identyfikator projektu','id');
      for(const [key,label]of[['fact_ids','Fakty'],['access_ids','Uprawnienia'],['custom_events','Zdarzenia z gry']])html+=detail(label,project[key].map((x,i)=>'<div class="fc-row">'+field('Nazwa',key+'.'+i)+btn('Usuń','remove',key+'.'+i,'fc-mini danger')+'</div>').join('')+btn('+ Dodaj','add-id',key),true);
      html+=detail('Przedmioty',project.items.map((x,i)=>'<div class="fc-card">'+field('Nazwa','items.'+i+'.display_name')+field('ID','items.'+i+'.id')+btn('Usuń','remove','items.'+i,'fc-mini danger')+'</div>').join('')+btn('+ Przedmiot','add-item','items'),true);
      html+='<p class="fc-note">Nowe zdarzenie wymaga emitowania z odpowiedniego systemu gry. Samo wpisanie nazwy nie dodaje mechaniki.</p>'+btn('Cofnij zmianę ustawień','undo')+btn('Ponów zmianę ustawień','redo');
    }else if(tab==='preview'){
      const result=compile(false),dd=result.bundle.dialogues.find(x=>x.id===d.id+'_dialogue'),line=W.line();let n=parsed().stages.flatMap(s=>s.nodes).filter(x=>!C.isPlayer(x)&&x.sourceLine<=line).at(-1);const rn=dd?.nodes.find(x=>x.id===n?.stableId)||dd?.nodes[0];
      html=title('Czytelność na telefonie','Orientacyjny podgląd proporcji 360 × 640. Docelową czcionkę i działanie wyborów sprawdź w Godocie.')+btn('Odśwież z miejsca kursora','refresh');
      if(rn)html+='<div class="fc-phone"><div class="fc-phone-panel"><div class="fc-phone-name">'+esc(rn.speaker)+'</div><div class="fc-phone-text">'+esc(rn.text)+'</div><div class="fc-phone-options">'+rn.choices.map(c=>'<div class="'+(c.text.length>40?'over':'')+'">'+esc(c.text)+'</div>').join('')+'</div></div></div>';
      html+='<p class="fc-note">Podgląd nie ucina treści. Długie wypowiedzi przewijasz; odpowiedzi należy skracać. Rzeczywisty panel gry rezerwuje trzy rzędy odpowiedzi i 172 px tekstu NPC.</p>'+btn('Sprawdź cały projekt','validate');
    }else{
      html=title('Od tekstu do gry','Flying Cab Story 1.1 · osobna wersja edytora v31.22.')+btn('Nowy quest od zera','new-quest')+'<ol class="fc-note"><li>Kliknij + Nowy quest. Wpisz nazwę, wybierz zleceniodawcę oraz bieżący albo osobny projekt.</li><li>Ustaw cele oraz nagrodę w panelu Zadanie.</li><li>Użyj karty Zacznij tutaj: dodaj cel i zastąp żółte wskazówki własną rozmową. Przyjęcie i oddanie są już połączone.</li><li>W panelu Odpowiedź wybierz warunki oraz skutki.</li><li>Zapisz projekt .fcstory — zawiera teksty i wszystkie ustawienia.</li><li>Eksport do Godota pobiera plik .json.</li><li>W Godocie: Projekt → Narzędzia → Flying Cab — importuj fabułę. Wybierz eksport.</li><li>Uruchom grę ponownie. Przykład jest nowym tematem u Froggy’ego.</li></ol><p class="fc-note">Projekt → Narzędzia → Flying Cab — podgląd fabuły otwiera prawdziwy panel rozmowy z osobną sesją, bez zapisu gracza.</p><p class="fc-note">Zdarzenia świata wykonują cele. Skok {ETAP_2} zmienia wypowiedź; sam w sobie nie przyjmuje ani nie kończy zadania. Komentarze //warunek są opisami — eksport wymaga ustawienia mechaniki w formularzach.</p>'+btn('Zapisz sam tekst rozmowy .txt','export-text')+btn('Wczytaj sam tekst .txt','import-text')+btn('Sprawdź cały projekt','validate');
    }
    props.innerHTML=html;[...props.querySelectorAll('details')].forEach(e=>{const key=e.querySelector('summary')?.textContent;if(opened.has(key))e.open=opened.get(key);});props.scrollTop=scroll;
  }
  function compile(stamp=true){syncText();if(stamp){for(const d of project.documents)d.text=C.stabilize(d.text,W);loading=true;W.setText(doc()?.text||'');loading=false;W.clean();}return C.compile(project,W,world);}
  function closeResult(){results.hidden=true;workspace.inert=false;$('.app-header').inert=false;}
  function showResult(title,html){$('#fc-result-title').textContent=title;$('#fc-result-body').innerHTML=html;results.hidden=false;workspace.inert=true;$('.app-header').inert=true;$('#fc-result-close').focus();}
  function report(result){return result.errors.map(e=>'<div class="fc-error">'+esc(e.message)+(e.doc?'<br><button class="fc-mini" data-error-doc="'+esc(e.doc)+'" data-line="'+(e.line??0)+'">Otwórz dokument</button>':'')+'</div>').join('')+result.warnings.map(e=>'<div class="fc-warning">'+esc(e.message)+'</div>').join('');}
  function download(value,name,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([value],{type}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function saveProject(){stabilize();download(JSON.stringify(project,null,2)+'\n',project.id+'.fcstory');dirty=false;$('#fc-dirty').textContent='Zapisano projekt';cache();}
  function exportGame(){try{const result=compile();cache();if(result.errors.length){showResult('Popraw przed importem',report(result));return;}download(JSON.stringify(result.bundle,null,2)+'\n',project.id+'.narrative.json');showResult('Eksport gotowy','<div class="fc-success">'+result.bundle.quests.length+' questów · '+result.bundle.dialogues.length+' rozmów. Plik eksportu został pobrany.</div><p>W Godocie wybierz <strong>Projekt → Narzędzia → Flying Cab — importuj fabułę</strong> i wskaż pobrany JSON. Następnie uruchom grę ponownie.</p><p>Do dalszego pisania zachowaj także <strong>projekt .fcstory</strong>. Eksport do gry jest jego pochodną.</p>'+report(result));}catch(e){showResult('Błąd eksportu','<div class="fc-error">'+esc(e.message)+'</div>');}}
  function addDoc(kind='dialogue'){syncText();remember();const npc=project.npcs[0]||{id:'froggy',display_name:'FROGGY'};project.documents.push(kind==='dialogue'?C.newConversation(npc.id,npc.display_name):C.wireTemplate(C.newDocument(npc.id,npc.display_name)));selectDoc(project.documents.length-1);changed();}
  function handleAction(action,path){
    if(action==='goal-flow'){syncText();const d=doc(),end=d.requires_turn_in?'Odbiór nagrody u '+(project.npcs.find(n=>n.id===d.turn_in_npc)?.display_name||d.turn_in_npc):'Ukończenie i nagroda';showResult('Przebieg celów · '+d.title,'<p>Początek → cel 1. Kliknij cel, aby zmienić jego ustawienia.</p>'+d.objectives.map((o,i)=>'<div class="fc-flow-card"><button class="fc-goal" data-flow-goal="'+i+'"><strong>'+(i+1)+'. '+esc(o.description)+'</strong></button><p>'+esc(o.mode==='event'?(C.EVENTS[o.event]+' × '+o.required):'Sprawdzenie stanu')+'</p>'+(o.transitions.length?o.transitions:[{target:d.objectives[i+1]?.id||'',conditions:[]}]).map(t=>'<div class="fc-flow-route">'+esc(t.conditions.length?t.conditions.map(c=>(c.invert?'NIE: ':'')+(C.CONDITIONS[c.kind]||c.kind)+(c.key?' '+c.key:'')+' '+(c.kind==='quest_status'?(C.STATUSES[c.status]||c.status):(c.comparison+' '+c.amount))).join(' oraz '):'Zawsze / w pozostałych przypadkach')+'<br><b>↳ '+esc(t.target?(d.objectives.findIndex(g=>g.id===t.target)+1)+'. '+(d.objectives.find(g=>g.id===t.target)?.description||'BRAK CELU'):end)+'</b></div>').join('')+'</div>').join(''));return;}
    if(action==='new-quest'){openCreator();return;}
    if(action==='guide-goals'){tab='quest';props.innerHTML='';render();$('#fc-goals-section').scrollIntoView({block:'start'});return;}
    if(action==='guide-text'){syncText();const lines=doc().text.split('\n'),i=lines.findIndex(line=>line.includes('⟪Uzupełnij:'));W.gotoLine(i<0?(parsed().stages[0]?.sourceLine||0):i);return;}
    if(action==='guide-details'){tab='quest';props.innerHTML='';render();const field=props.querySelector('[data-path="documents.'+docIndex+'.description"]');field?.focus();return;}
    if(action==='hide-guide'){syncText();remember();doc().authoring.guide_dismissed=true;changed();render();return;}
    if(action==='refresh'){syncText();render();return;}if(action==='validate'){const r=compile();showResult(r.errors.length?'Popraw projekt':'Projekt poprawny',(r.errors.length?'':'<div class="fc-success">Struktura i odwołania są poprawne. Przebieg rozgrywki sprawdź w Godocie.</div>')+report(r));return;}
    if(action==='stabilize'){stabilize();render();return;}if(action==='import-text'){$('#fc-text-file').click();return;}if(action==='export-text'){syncText();download(W.normalize(doc().text),doc().id+'.txt','text/plain');return;}
    if(action==='goto-stage'){W.gotoLine(parsed().stageMap[stageId]?.sourceLine||0);return;}
    if(action==='choice-cursor'){const line=W.line();stabilize();const choices=parsed().stages.flatMap(s=>s.nodes.flatMap(n=>n.options));choiceId=choices.filter(c=>c.sourceLine<=line).at(-1)?.stableId||choices[0]?.stableId||'';render();return;}
    if(action==='undo'||action==='redo'){syncText();const from=action==='undo'?undo:redo,to=action==='undo'?redo:undo;if(from.length){to.push(JSON.stringify(project));project=JSON.parse(from.pop());selectDoc(docIndex,false);changed();}return;}
    syncText();remember();
    if(action==='add-condition')get(path).push(C.condition());
    else if(action==='add-effect')get(path).push(C.effect());
    else if(action==='add-objective'){get(path).push(C.emptyObjective());goalIndex=get(path).length-1;}
    else if(action==='remove'){const a=path.split('.'),i=Number(a.pop());get(a.join('.')).splice(i,1);}
    else if(action==='delete-key'){const a=path.split('.'),key=a.pop();delete get(a.join('.'))[key];}
    else if(action==='up'){const a=path.split('.'),i=Number(a.pop()),list=get(a.join('.'));if(i>0){[list[i-1],list[i]]=[list[i],list[i-1]];goalIndex=i-1;}}
    else if(action==='add-route'){const list=get(path),next=doc().objectives[goalIndex+1]?.id||'';if(!list.length)list.push({target:next,conditions:[]});list.splice(list.length-1,0,{target:next,conditions:[C.condition()]});}
    else if(action==='add-id')get(path).push(C.uid(path==='fact_ids'?'fakt':path==='access_ids'?'dostep':'zdarzenie'));
    else if(action==='add-item')project.items.push({id:C.uid('item'),display_name:'Nowy przedmiot'});
    else if(action==='add-npc'){const n={id:C.uid('npc'),display_name:'NOWA POSTAĆ',greeting:'O czym chcesz porozmawiać?',existing:false,portrait:''};project.npcs.push(n);npcId=n.id;}
    else if(action==='add-stage'){const ids=new Set(parsed().stages.map(s=>s.id));let i=1;while(ids.has('ETAP_'+i))i++;const id='ETAP_'+i,npc=project.npcs.find(n=>n.id===doc().npc);const text='\n###ETAP\n'+id+' ###Nowa rozmowa ###\n##DIALOG *'+(npc?.display_name||'FROGGY')+'*\n*'+(npc?.display_name||'FROGGY')+'*\nNowa wypowiedź.\n*GRACZ*\nDo zobaczenia.{-1}\n';doc().text=doc().text.replace(/\s*##END\s*$/,'')+text+'\n##END\n';doc().text=C.stabilize(doc().text,W);doc().stages[id]={status:'none',conditions:[]};stageId=id;loading=true;W.setText(doc().text);loading=false;}
    else if(action==='duplicate-doc'){const copy=C.clone(doc()),oldId=copy.id;copy.id=C.uid('quest');copy.title+=' — kopia';copy.version=1;copy.text=copy.text.replace('##QUEST###'+oldId,'##QUEST###'+copy.id);for(const choice of Object.values(copy.choices))for(const e of choice.effects)if(['start_quest','turn_in'].includes(e.kind)&&e.key===oldId)e.key=copy.id;project.documents.push(copy);selectDoc(project.documents.length-1);}
    changed();renderDocumentPicker();render();
  }
  $('.fc-tabs').addEventListener('click',e=>{if(!e.target.dataset.tab)return;syncText();tab=e.target.dataset.tab;props.innerHTML='';if(tab==='choice')stabilize();render();});
  // Ordinary fields update while typing; saving or switching controls must not lose
  // the final edit. Identity changes still commit on change, after the name is complete.
  let editedField=null;
  props.addEventListener('input',e=>{
    const field=e.target,path=field.dataset.path;
    if(!path||!['text','textarea','number'].includes(field.type)||/\.(id|display_name)$/.test(path)||/^(id|fact_ids\.|access_ids\.|custom_events\.)/.test(path))return;
    const value=field.type==='number'?Number(field.value):field.value;
    if(field.type==='number'&&(field.value===''||!Number.isFinite(value)))return;
    if(get(path)===value)return;
    if(editedField!==field){remember();editedField=field;}
    C.updateField(project,path,value);changed();renderDocumentPicker();
  });
  props.addEventListener('change',e=>{
    if(e.target.id==='fc-stage'){stageId=e.target.value;render();return;}if(e.target.id==='fc-choice'){choiceId=e.target.value;render();return;}if(e.target.id==='fc-npc'){npcId=e.target.value;render();return;}
    const path=e.target.dataset.path;if(!path)return;syncText();const value=e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?Number(e.target.value):e.target.dataset.type==='multi'?[...e.target.selectedOptions].map(x=>x.value):e.target.value;try{if(JSON.stringify(get(path))!==JSON.stringify(value))remember();C.updateField(project,path,value);if(path.endsWith('.mode'))props.innerHTML='';loading=true;W.setText(doc().text);loading=false;changed();renderDocumentPicker();render();}catch(err){showResult('Nieprawidłowa wartość','<div class="fc-error">'+esc(err.message)+'</div>');render();}
  });
  props.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-goal]');if(!b)return;if(b.dataset.goal!==undefined){goalIndex=Number(b.dataset.goal);render();return;}try{handleAction(b.dataset.action,b.dataset.path);}catch(err){showResult('Nie udało się wykonać zmiany','<div class="fc-error">'+esc(err.message)+'</div>');}});
  $('#fc-document').addEventListener('change',e=>selectDoc(Number(e.target.value)));$('#fc-new').addEventListener('click',openCreator);$('#fc-new-talk').addEventListener('click',()=>addDoc('dialogue'));$('#fc-save').addEventListener('click',saveProject);$('#fc-export').addEventListener('click',exportGame);$('#fc-toggle').addEventListener('click',()=>{inspector.hidden=!inspector.hidden;W.refresh();});
  $('#fc-open').addEventListener('click',()=>$('#fc-file').click());$('#fc-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const p=C.checkProject(JSON.parse(await file.text()));if(dirty&&!confirm('Zastąpić bieżący projekt? Niezapisane zmiany zostaną utracone. Anuluj i zapisz plik, jeśli chcesz je zachować.'))return;loadProject(p);}catch(err){showResult('Nie można otworzyć projektu','<div class="fc-error">'+esc(err.message)+'</div>');}finally{e.target.value='';}});
  $('#fc-text-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(!confirm('Zastąpić tekst bieżącego dokumentu? Ustawienia zapisane dla usuniętych odpowiedzi nie zostaną przeniesione na nowe.'))return;syncText();remember();doc().text=C.stabilize(await file.text(),W);doc().choices={};doc().stages={};for(const s of C.indexed(doc().text,W).stages)doc().stages[s.id]={status:'none',conditions:[]};selectDoc(docIndex,false);changed();e.target.value='';});
  $('#fc-result-close').addEventListener('click',closeResult);results.addEventListener('click',e=>{const g=e.target.closest('[data-flow-goal]');if(g){goalIndex=Number(g.dataset.flowGoal);tab='quest';closeResult();render();return;}const b=e.target.closest('[data-error-doc]');if(b){selectDoc(project.documents.findIndex(d=>d.id===b.dataset.errorDoc));closeResult();W.gotoLine(Number(b.dataset.line));}});
  document.addEventListener('input',e=>{if(e.target.closest('.app-main')){clearTimeout(timer);timer=setTimeout(syncText,400);}},true);
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();e.stopImmediatePropagation();saveProject();}if(e.key==='Escape'&&!results.hidden){e.preventDefault();closeResult();}},true);
  setInterval(syncText,1000);
  window.addEventListener('beforeunload',e=>{syncText();cache();if(dirty){e.preventDefault();e.returnValue='';}});
  // Whole-project draft is distinct from upstream writer autosaves.
  try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved){project=C.checkProject(saved.project);docIndex=Math.min(saved.docIndex||0,project.documents.length-1);dirty=true;}}catch(e){cacheAllowed=false;showResult('Szkic wymaga uwagi','<p>Nie udało się odczytać szkicu. Otwórz ostatni zapisany projekt .fcstory. Uszkodzony szkic pozostaje w pamięci przeglądarki do czasu następnego zapisu.</p>');}
  for(const n of project.npcs)if(!Object.hasOwn(n,'portrait'))n.portrait='';
  selectDoc(docIndex,false);$('#fc-dirty').textContent=dirty?'Przywrócony szkic':'Przykład do edycji';
})();
