#!/usr/bin/env python3
"""Refresh editor pickers from the Flying Cab source files (no game generation)."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GAME = ROOT / 'godot/FlyingCabPrototype'

def fields(path):
    text = path.read_text()
    resource = text.split('[resource]')[-1]
    return dict(re.findall(r'^([a-z_]+) = &?"([^"\n]*)"', resource, re.M))

def main():
    base = GAME / 'resources/narrative'
    catalog = (base / 'city_catalog.tres').read_text()
    by_id = {m[1]: GAME / m[0].removeprefix('res://') for m in re.findall(r'\[ext_resource[^\n]*path="([^"]+)"[^\n]*id="([^"]+)"\]', catalog)}
    world = {}
    for group in ('npcs', 'quests', 'items'):
        line = next((l for l in catalog.splitlines() if l.startswith(group + ' =')), '')
        records = []
        for rid in re.findall(r'ExtResource\("([^"]+)"\)', line)[1:]:
            data = fields(by_id[rid])
            record = {k: data[k] for k in ('id','display_name','title','greeting') if k in data}
            if group == 'npcs':
                record.update(existing=True, portrait='', profile_path='res://' + str(by_id[rid].relative_to(GAME)))
            records.append(record)
        world[group] = records
    for group in ('fact_ids','access_ids','custom_events'):
        match = re.search(r'^' + group + r' = PackedStringArray\((.*)\)', catalog, re.M)
        world[group] = re.findall(r'"([^"]+)"', match[1]) if match else []
    city = (GAME / 'scenes/city.tscn').read_text()
    world['stops'] = [{'id': a, 'display_name': b} for a,b in re.findall(r'stop_id = "([^"]+)"\ndisplay_name = "([^"]+)"', city)]
    world['models'] = []
    for path in sorted((GAME / 'resources').rglob('*.tres')):
        if 'script_class="VehicleDefinition"' in path.read_text()[:300]:
            data = fields(path)
            if data.get('id') or data.get('model_id'):
                world['models'].append({'id': data.get('id',data.get('model_id')), 'display_name':data.get('display_name',path.stem)})
    world['vehicles'] = [{'id':'ari_cab','display_name':'Cab Ariego'}]
    fleet = (GAME / 'scenes/foundry_test_fleet.tscn').read_text()
    for vehicle_id in re.findall(r'entity_id = &"([^"]+)"', fleet):
        world['vehicles'].append({'id': vehicle_id, 'display_name': 'Test Fleet / ' + vehicle_id.split('/')[-1]})
    living = (GAME / 'resources/living_world/city_02.tres').read_text()
    for resident_id in re.findall(r'resident_id = "([^"]+)"', living):
        world['vehicles'].append({'id': 'resident/' + resident_id, 'display_name': 'Mieszkaniec / ' + resident_id})
    for block in living.split('[sub_resource'):
        route = re.search(r'route_id = "([^"]+)"', block)
        count = re.search(r'population = (\d+)', block)
        if route and count:
            for i in range(int(count[1])):
                vehicle_id = 'traffic/' + route[1] + '/%02d' % i
                world['vehicles'].append({'id': vehicle_id, 'display_name': vehicle_id})
    target = Path(__file__).with_name('world-catalog.js')
    target.write_text('/* Flying Cab 1.0 — generated by update_world_catalog.py. */\nwindow.FCWorld = ' + json.dumps(world, ensure_ascii=False, indent=2) + ';\n')
    print('World pickers:', len(world['npcs']), 'NPC,', len(world['stops']), 'stops')

if __name__ == '__main__':
    main()
