/* Flying Cab 1.0 — generated by update_world_catalog.py. */
window.FCWorld = {
  "npcs": [
    {
      "id": "maya",
      "display_name": "MAYA",
      "greeting": "Dobrze cię widzieć, Ari.",
      "existing": true,
      "portrait": "",
      "profile_path": "res://resources/narrative/maya.tres"
    },
    {
      "id": "froggy",
      "display_name": "FROGGY",
      "greeting": "Czego potrzebujesz, kierowco?",
      "existing": true,
      "portrait": "",
      "profile_path": "res://resources/narrative/froggy.tres"
    }
  ],
  "quests": [
    {
      "id": "first_dose",
      "title": "Czas dla siostry"
    },
    {
      "id": "froggy_favor",
      "title": "Zaufanie Froggy’ego"
    },
    {
      "id": "depot_driver",
      "title": "Depot driver"
    }
  ],
  "items": [
    {
      "id": "froggy_note",
      "display_name": "Notatka Froggy’ego"
    }
  ],
  "fact_ids": [
    "promised_froggy"
  ],
  "access_ids": [],
  "custom_events": [],
  "stops": [
    {
      "id": "depot",
      "display_name": "DEPOT ARIEGO"
    },
    {
      "id": "velvet_neon",
      "display_name": "VELVET / BAR"
    },
    {
      "id": "velvet_club",
      "display_name": "VELVET / ROOM 09"
    },
    {
      "id": "foundry_market",
      "display_name": "FOUNDRY / OCTANE"
    },
    {
      "id": "foundry_docks",
      "display_name": "FOUNDRY / NIGHT SHIFT"
    },
    {
      "id": "foundry_torque",
      "display_name": "FOUNDRY / TORQUE"
    },
    {
      "id": "velvet_03",
      "display_name": "VELVET / SUGAR CLUB"
    },
    {
      "id": "eden_01",
      "display_name": "EDEN / EDEN CLINIC"
    },
    {
      "id": "eden_02",
      "display_name": "EDEN / SOMA"
    },
    {
      "id": "eden_03",
      "display_name": "EDEN / NEW SELF"
    },
    {
      "id": "velvet_04",
      "display_name": "VELVET / LOVE HOTEL"
    },
    {
      "id": "velvet_05",
      "display_name": "VELVET / LAST KISS"
    },
    {
      "id": "eden_04",
      "display_name": "EDEN / LUCENT"
    },
    {
      "id": "eden_05",
      "display_name": "EDEN / BLOOM"
    },
    {
      "id": "velvet_06",
      "display_name": "VELVET / BLUE HOUR"
    },
    {
      "id": "eden_06",
      "display_name": "EDEN / HALO HEALTH"
    },
    {
      "id": "aurelia_01",
      "display_name": "AURELIA / AURELIA"
    },
    {
      "id": "aurelia_02",
      "display_name": "AURELIA / CROWN BANK"
    },
    {
      "id": "aurelia_03",
      "display_name": "AURELIA / MERIDIAN"
    },
    {
      "id": "foundry_04",
      "display_name": "FOUNDRY / GRIDWORKS"
    },
    {
      "id": "foundry_05",
      "display_name": "FOUNDRY / EAST EXCHANGE"
    },
    {
      "id": "aurelia_04",
      "display_name": "AURELIA / HELIOS"
    },
    {
      "id": "aurelia_05",
      "display_name": "AURELIA / VAULT 01"
    },
    {
      "id": "foundry_06",
      "display_name": "FOUNDRY / AFTERMARKET"
    },
    {
      "id": "aurelia_06",
      "display_name": "AURELIA / APEX CAPITAL"
    }
  ],
  "models": [
    {
      "id": "basic_cab",
      "display_name": "Ari / Cab"
    },
    {
      "id": "heavy_shuttle",
      "display_name": "Foundry / Shuttle"
    },
    {
      "id": "limousine",
      "display_name": "Limousine"
    },
    {
      "id": "lorry",
      "display_name": "Lorry"
    },
    {
      "id": "luxury_car",
      "display_name": "Luxury car"
    },
    {
      "id": "normal_car_1",
      "display_name": "Normal / Violet"
    },
    {
      "id": "normal_car_2",
      "display_name": "Normal / Graphite"
    },
    {
      "id": "normal_car_3",
      "display_name": "Normal / Copper"
    },
    {
      "id": "police_car",
      "display_name": "Police car"
    },
    {
      "id": "poor_car",
      "display_name": "Poor car"
    },
    {
      "id": "supercar",
      "display_name": "Supercar"
    },
    {
      "id": "tow_car",
      "display_name": "Tow car"
    }
  ],
  "vehicles": [
    {
      "id": "ari_cab",
      "display_name": "Cab Ariego"
    },
    {
      "id": "test_fleet/basic_cab",
      "display_name": "Test Fleet / basic_cab"
    },
    {
      "id": "test_fleet/heavy_shuttle",
      "display_name": "Test Fleet / heavy_shuttle"
    },
    {
      "id": "test_fleet/lorry",
      "display_name": "Test Fleet / lorry"
    },
    {
      "id": "test_fleet/supercar",
      "display_name": "Test Fleet / supercar"
    },
    {
      "id": "test_fleet/limousine",
      "display_name": "Test Fleet / limousine"
    },
    {
      "id": "test_fleet/luxury_car",
      "display_name": "Test Fleet / luxury_car"
    },
    {
      "id": "test_fleet/police_car",
      "display_name": "Test Fleet / police_car"
    },
    {
      "id": "test_fleet/poor_car",
      "display_name": "Test Fleet / poor_car"
    },
    {
      "id": "test_fleet/tow_car",
      "display_name": "Test Fleet / tow_car"
    },
    {
      "id": "test_fleet/normal_car_1",
      "display_name": "Test Fleet / normal_car_1"
    },
    {
      "id": "test_fleet/normal_car_2",
      "display_name": "Test Fleet / normal_car_2"
    },
    {
      "id": "test_fleet/normal_car_3",
      "display_name": "Test Fleet / normal_car_3"
    },
    {
      "id": "resident/velvet_commuter",
      "display_name": "Mieszkaniec / velvet_commuter"
    },
    {
      "id": "resident/foundry_commuter",
      "display_name": "Mieszkaniec / foundry_commuter"
    },
    {
      "id": "resident/eden_commuter",
      "display_name": "Mieszkaniec / eden_commuter"
    },
    {
      "id": "resident/aurelia_commuter",
      "display_name": "Mieszkaniec / aurelia_commuter"
    },
    {
      "id": "resident/hotel_owner",
      "display_name": "Mieszkaniec / hotel_owner"
    },
    {
      "id": "resident/club_owner",
      "display_name": "Mieszkaniec / club_owner"
    },
    {
      "id": "resident/mechanic",
      "display_name": "Mieszkaniec / mechanic"
    },
    {
      "id": "resident/hauler",
      "display_name": "Mieszkaniec / hauler"
    },
    {
      "id": "resident/clinic_owner",
      "display_name": "Mieszkaniec / clinic_owner"
    },
    {
      "id": "resident/surgeon",
      "display_name": "Mieszkaniec / surgeon"
    },
    {
      "id": "resident/banker",
      "display_name": "Mieszkaniec / banker"
    },
    {
      "id": "resident/patrol_owner",
      "display_name": "Mieszkaniec / patrol_owner"
    },
    {
      "id": "traffic/outer_clockwise/00",
      "display_name": "traffic/outer_clockwise/00"
    },
    {
      "id": "traffic/outer_clockwise/01",
      "display_name": "traffic/outer_clockwise/01"
    },
    {
      "id": "traffic/outer_clockwise/02",
      "display_name": "traffic/outer_clockwise/02"
    },
    {
      "id": "traffic/outer_clockwise/03",
      "display_name": "traffic/outer_clockwise/03"
    },
    {
      "id": "traffic/outer_clockwise/04",
      "display_name": "traffic/outer_clockwise/04"
    },
    {
      "id": "traffic/outer_clockwise/05",
      "display_name": "traffic/outer_clockwise/05"
    },
    {
      "id": "traffic/outer_clockwise/06",
      "display_name": "traffic/outer_clockwise/06"
    },
    {
      "id": "traffic/outer_clockwise/07",
      "display_name": "traffic/outer_clockwise/07"
    },
    {
      "id": "traffic/outer_clockwise/08",
      "display_name": "traffic/outer_clockwise/08"
    },
    {
      "id": "traffic/outer_clockwise/09",
      "display_name": "traffic/outer_clockwise/09"
    },
    {
      "id": "traffic/outer_counterclockwise/00",
      "display_name": "traffic/outer_counterclockwise/00"
    },
    {
      "id": "traffic/outer_counterclockwise/01",
      "display_name": "traffic/outer_counterclockwise/01"
    },
    {
      "id": "traffic/outer_counterclockwise/02",
      "display_name": "traffic/outer_counterclockwise/02"
    },
    {
      "id": "traffic/outer_counterclockwise/03",
      "display_name": "traffic/outer_counterclockwise/03"
    },
    {
      "id": "traffic/outer_counterclockwise/04",
      "display_name": "traffic/outer_counterclockwise/04"
    },
    {
      "id": "traffic/outer_counterclockwise/05",
      "display_name": "traffic/outer_counterclockwise/05"
    },
    {
      "id": "traffic/outer_counterclockwise/06",
      "display_name": "traffic/outer_counterclockwise/06"
    },
    {
      "id": "traffic/outer_counterclockwise/07",
      "display_name": "traffic/outer_counterclockwise/07"
    },
    {
      "id": "traffic/spine/00",
      "display_name": "traffic/spine/00"
    },
    {
      "id": "traffic/spine/01",
      "display_name": "traffic/spine/01"
    },
    {
      "id": "traffic/spine/02",
      "display_name": "traffic/spine/02"
    },
    {
      "id": "traffic/spine/03",
      "display_name": "traffic/spine/03"
    },
    {
      "id": "traffic/spine/04",
      "display_name": "traffic/spine/04"
    },
    {
      "id": "traffic/spine/05",
      "display_name": "traffic/spine/05"
    },
    {
      "id": "traffic/crosstown/00",
      "display_name": "traffic/crosstown/00"
    },
    {
      "id": "traffic/crosstown/01",
      "display_name": "traffic/crosstown/01"
    },
    {
      "id": "traffic/crosstown/02",
      "display_name": "traffic/crosstown/02"
    },
    {
      "id": "traffic/crosstown/03",
      "display_name": "traffic/crosstown/03"
    },
    {
      "id": "traffic/crosstown/04",
      "display_name": "traffic/crosstown/04"
    },
    {
      "id": "traffic/crosstown/05",
      "display_name": "traffic/crosstown/05"
    },
    {
      "id": "traffic/velvet/00",
      "display_name": "traffic/velvet/00"
    },
    {
      "id": "traffic/velvet/01",
      "display_name": "traffic/velvet/01"
    },
    {
      "id": "traffic/foundry/00",
      "display_name": "traffic/foundry/00"
    },
    {
      "id": "traffic/foundry/01",
      "display_name": "traffic/foundry/01"
    },
    {
      "id": "traffic/eden/00",
      "display_name": "traffic/eden/00"
    },
    {
      "id": "traffic/eden/01",
      "display_name": "traffic/eden/01"
    },
    {
      "id": "traffic/aurelia/00",
      "display_name": "traffic/aurelia/00"
    },
    {
      "id": "traffic/aurelia/01",
      "display_name": "traffic/aurelia/01"
    }
  ]
};
